import Image from "next/image"

const Marquee = () => {
  return (
    <div className="section-logo-marquee padding-horizontal-vertical">
      <div className="marquee">
        <div className="marquee-content scroll">
          <Image
            src="/images/HDFC.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Groww.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Bajaj-Finserve.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/B612.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Alibabagroup.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Cred.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Tata-1mg.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Urban-company.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
        </div>
        <div className="marquee-content scroll">
          <Image
            src="/images/Kotak.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Dunzo.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Dream11.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Airtel.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/ZEE.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/OYO.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Josh.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="/images/Share-Chat.svg"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
        </div>
        {/* Add more marquee-content divs for additional rows */}
        <div className="marquee-content scroll">
          <Image
            src="images/Make-My-Trip.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Goibibo.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/ixigo.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Yatra.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Nykaa.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Myntra.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Snapdeal.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
        </div>
        <div className="marquee-content scroll">
          <Image
            src="images/IDFC.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Yes-Bank.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Edelweiss.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/ELSA.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/CoinMArketcap.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/SimpleLearn.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/BYJUs-Exam-Prep.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/mint.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
        </div>
        <div className="marquee-content scroll">
          <Image
            src="images/Magicbricks.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Housing.com.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Nobroker.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Ultrahuman.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Fynd.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Fancode.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/fectar.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/One-code_ZET.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
        </div>
        <div className="marquee-content scroll">
          <Image
            src="images/HDFC.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Groww.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Bajaj-Finserve.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/B612.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Alibabagroup.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Cred.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Tata-1mg.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
          <Image
            src="images/Urban-company.svg"
            loading="eager"
            width={120}
            height={120}
            alt=""
            className="marquee-image"
          />
        </div>
      </div>
    </div>
  )
}

export default Marquee
